### ISSUE TITLE
Didn't Integrate the React-Native CLI APP

### ISSUE THREAD

**Issue by leonardo116** [WrathChaos/react-native-helpers#1]
I've just created the react-native hello world app by used react-native-cli.
And I integrated the react-native-helpers after add dependency and install it.
Unfortunately I've got some error like that "Module AppRegistry is not registered callable module (calling runApplication)

Let me know someone who solved it.

**Comment by WrathChaos** [comment]
Hello @richard8301,
After 0.0.2 version, you need to link "@react-native-community/status-bar". After RN 0.60 they removed the StatusBar from react-native itself.
