### ISSUE TITLE
hasNotch always return true

### ISSUE THREAD

**Issue by ugrdursun** [WrathChaos/react-native-helpers#15]
hasNotch is returning true on non-notch devices and android devices also.

My RNVersion is 0.61.5 and library version is latest.

What could be the problem ?

**Comment by WrathChaos** [comment]
Hello @ugrdursun 
Thank you for reporting this. Have you also tested it on iOS devices as well? 

I will take a look for Android devices

**Comment by WrathChaos** [comment]
Yep, library does not have a check for Android on `hasNotch` function but it should work on iOS. I will add it for Android ASAP.

**Comment by ugrdursun** [comment]
> Hello @ugrdursun
> Thank you for reporting this. Have you also tested it on iOS devices as well?
> 
> I will take a look for Android devices

Hi, yes it returns true always on iOS devices too. Tested with iPhone 8 iPhone 12 and 12 mini, and iPhone SE. Also isiPhoneNotchFamily always returns true. (all tested on simulator)

**Comment by WrathChaos** [comment]
I'm testing them thank you :)

**Comment by WrathChaos** [comment]
Hello @ugrdursun,
I've updated the example and tested it on iOS. It works on the example, can you try it?

<img width="895" alt="CleanShot 2021-06-09 at 8 37 53@2x" src="https://user-images.githubusercontent.com/6813862/121403654-c93b8b00-c963-11eb-9afc-ffe40de0ec05.png">


Android support for the notch is incoming.

**Comment by ugrdursun** [comment]
> Hello @ugrdursun,
> I've updated the example and tested it on iOS. It works on the example, can you try it?
> 
> <img alt="CleanShot 2021-06-09 at 8 37 53@2x" width="895" src="https://user-images.githubusercontent.com/6813862/121403654-c93b8b00-c963-11eb-9afc-ffe40de0ec05.png">
> 
> Android support for the notch is incoming.


```
import {
  isIPhoneNotchFamily,
  isIPhone11,
  isIPhone12,
  isIPhone12Mini,
  isIPhone12ProMax,
  hasNotch,
  isIPhoneX,
  isIPhoneXr,
  isIPhoneXs,
  isIPhoneXsMax,
  getStatusBarHeight,
} from "@freakycoder/react-native-helpers";


...

  componentDidMount() {

    console.log(hasNotch ? 'yes' : 'no')



  }
```

just tried with a clean new RN 0.63.4, the code above returns yes on iphone 8 simulator :(

iOS ver: 14.4
RN ver 0.63.4
library ver @latest

I couldn't figure it out

**Comment by WrathChaos** [comment]
@ugrdursun you do not call the function. Try with this: `hasNotch()`

**Comment by ugrdursun** [comment]
> @ugrdursun you do not call the function. Try with this: `hasNotch()`

Sorry for my bad :( It's Working thanks!

**Comment by WrathChaos** [comment]
@ugrdursun  Feel free to open issue if you encounter any problem or a feature :)
