### ISSUE TITLE
can not find deepmerge library

### ISSUE THREAD

**Issue by palakornv** [WrathChaos/react-native-helpers#3]
I try the newest version, it causes an error when I build mine react native program. It shows some errors about the deepmerge, I have to switch back to the previous version and it works with the old "react-native-helpers"

**Comment by WrathChaos** [comment]
Hello @palakornv, 
There is a breaking change for the newest version for `isIPhoneXFamily`. It is renamed and re-functioned with `isIPhoneNotchFamily`. You should change it and it should not cause any error. Also please upload the screenshot the error :)

**Comment by WrathChaos** [comment]
## [Changelog](https://github.com/WrathChaos/react-native-helpers#changelog)

Here is the **Changelog** :)
